FROM node:21-alpine AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
COPY ./server /app
COPY ./.env /.env
WORKDIR /app

FROM base AS prod-deps
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --prod --frozen-lockfile

FROM base
ENV PROJ_SERVER_PORT=8001
COPY --from=prod-deps /app/node_modules /app/node_modules
EXPOSE $PROJ_SERVER_PORT
ENTRYPOINT [ "pnpm", "start" ]